"""Change enum to integer

Revision ID: 3455a5e32f60
Revises: 92d69baf99d8
Create Date: 2020-04-10 22:11:28.726430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3455a5e32f60'
down_revision = '92d69baf99d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_user', sa.Column('_rank', sa.Integer(), nullable=True))
    op.drop_column('organization_user', 'rank')
    op.add_column('organizations', sa.Column('_status', sa.Integer(), nullable=True))
    op.drop_column('organizations', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('status', postgresql.ENUM('pending', 'approved', 'denied', name='organizationstatus'), autoincrement=False, nullable=True))
    op.drop_column('organizations', '_status')
    op.add_column('organization_user', sa.Column('rank', postgresql.ENUM('owner', 'admin', 'active_member', 'inactive_member', name='organizationrank'), autoincrement=False, nullable=True))
    op.drop_column('organization_user', '_rank')
    # ### end Alembic commands ###
