"""Added cascade to comments.

Revision ID: 540355492dbc
Revises: f6a59fcb28c2
Create Date: 2020-04-06 14:00:53.072542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540355492dbc'
down_revision = 'f6a59fcb28c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'events', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'events', ['post_id'], ['id'])
    # ### end Alembic commands ###
