"""empty message

Revision ID: 874e0461616c
Revises: e9530407dda9
Create Date: 2020-03-19 23:43:14.853224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874e0461616c'
down_revision = 'e9530407dda9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_number', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_number')
    # ### end Alembic commands ###
