"""Change table name from events to posts

Revision ID: 9885404c0d0b
Revises: 540355492dbc
Create Date: 2020-04-06 14:01:08.541598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9885404c0d0b'
down_revision = '540355492dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('author_org_id', sa.Integer(), nullable=True),
    sa.Column('datetime_posted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'events', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('datetime_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_org_id'], ['organizations.id'], name='events_author_org_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name='events_author_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='events_pkey')
    )
    op.drop_table('posts')
    # ### end Alembic commands ###
