"""Added cascade.

Revision ID: f6a59fcb28c2
Revises: d4f11eacd2ab
Create Date: 2020-04-06 13:58:14.390373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a59fcb28c2'
down_revision = 'd4f11eacd2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_author_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_author_org_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'organizations', ['author_org_id'], ['id'], ondelete='CASCADE')
    op.add_column('events', sa.Column('datetime_posted', sa.DateTime(), nullable=True))
    op.drop_constraint('events_author_user_id_fkey', 'events', type_='foreignkey')
    op.drop_constraint('events_author_org_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['author_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'events', 'organizations', ['author_org_id'], ['id'], ondelete='CASCADE')
    op.drop_column('events', 'date_posted')
    op.drop_constraint('organization_user_organization_id_fkey', 'organization_user', type_='foreignkey')
    op.drop_constraint('organization_user_user_id_fkey', 'organization_user', type_='foreignkey')
    op.create_foreign_key(None, 'organization_user', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'organization_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_user', type_='foreignkey')
    op.drop_constraint(None, 'organization_user', type_='foreignkey')
    op.create_foreign_key('organization_user_user_id_fkey', 'organization_user', 'users', ['user_id'], ['id'])
    op.create_foreign_key('organization_user_organization_id_fkey', 'organization_user', 'organizations', ['organization_id'], ['id'])
    op.add_column('events', sa.Column('date_posted', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_author_org_id_fkey', 'events', 'organizations', ['author_org_id'], ['id'])
    op.create_foreign_key('events_author_user_id_fkey', 'events', 'users', ['author_user_id'], ['id'])
    op.drop_column('events', 'datetime_posted')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_author_org_id_fkey', 'comments', 'organizations', ['author_org_id'], ['id'])
    op.create_foreign_key('comments_author_user_id_fkey', 'comments', 'users', ['author_user_id'], ['id'])
    # ### end Alembic commands ###
